# Configure MariaDB and Log Mapper server.

FROM python:alpine

# Get code into container
RUN mkdir /mapper-server
ADD ./requirements.txt /mapper-server/requirements.txt
WORKDIR /mapper-server

# Install dependencies
RUN apk update &&\
apk add python3 python3-dev mariadb-dev build-base &&\
pip3 install mysqlclient &&\
pip3 install -r requirements.txt &&\
apk del python3-dev mariadb-dev build-base &&\
apk add mariadb-client-libs

ADD . /mapper-server
RUN mkdir /mapper-server/res/html/maps/

ADD crontab /etc/crontabs/root

CMD python3 draw_map.py

# Start server
CMD python3 server.py

EXPOSE 5000
